# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="f09b2fce-4428-416b-b047-0a423948b4f0"
# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - ivs1996@mail.ru
      - djkill59@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

    codecov:
      require_ci_to_pass: yes

    coverage:
      precision: 2
      round: down
      range: "10...15"

    parsers:
      gcov:
        branch_detection:
          conditional: yes
          loop: yes
          method: no
          macro: no

    comment:
      layout: "reach,diff,flags,tree"
      behavior: default
      require_changes: no